import type { Metadata } from 'next';
import { Space_Grotesk, Space_Mono } from 'next/font/google';
import './globals.css';
import { TRPCReactProvider } from '@/trpc/client';
import { Toaster } from '@/components/ui/sonner';

const primaryFont = Space_Grotesk({
        variable: '--font-primary',
        subsets: ['latin'],
});

const secondaryFont = Space_Mono({
        variable: '--font-secondary',
        weight: ['400', '700'],
        subsets: ['latin'],
});

export const metadata: Metadata = {
        title: 'Create Next App',
        description: 'Generated by create next app',
};

export default function RootLayout({
        children,
}: Readonly<{
        children: React.ReactNode;
}>) {
        return (
                <html lang="en">
                        <body className={`${primaryFont.variable} ${secondaryFont.variable} antialiased`}>
                                <TRPCReactProvider>
                                        <Toaster />
                                        {children}
                                </TRPCReactProvider>
                        </body>
                </html>
        );
}
